pages:
  - page_name: Home
    icon: ğŸ 
    script_path: streamlit_app.py
    layout: wide  # By default, layout is 'centered' for all pages
sections:
  - name: Utility Apps
    icon: â­
    pages:
      - page_name: Example One
        icon: ğŸ¤ 
        date_added: 2022-07-04  # If younger than a month, the page name will be augmented with a neat :new: emoji!
      - page_name: Custom name!  # Explicit naming here overwrites the name inferred from script_path
        icon: âš¡
        script_path: pages/example_two.py
  - name: More Apps
    icon: ğŸ’»
    pages:
      - page_name: Example three
        icon: ğŸ¦‡
      - page_name: Old App
        icon: ğŸ’€
        visible: false  # This app will not appear in the menu!
