pages:
  - page_name: Home
    icon: ğŸ 
    script_path: streamlit_app.py
    layout: wide
sections:
  - name: Utilty Apps
    icon: â­
    pages:
      - page_name: Example One
        icon: ğŸ¤ 
        date_added: 2022-07-04
      - page_name: Custom name!
        icon: âš¡
        script_path: pages/example_two.py
  - name: More Apps
    icon: ğŸ’»
    pages:
      - page_name: Example three
        icon: ğŸ¦‡
      - page_name: Old App
        icon: ğŸ’€
        deprecated: true